package com.puntos.utils;

public class ConstantJsonCMC {
	
	public static final String CMC_REQUEST_CONCUENTAS = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"IVR\",\r\n"
			+ "        \"_serviceId\": \"InstallmentPurchases\",\r\n"
			+ "        \"_datetime\": \"2020-03-31T18:59:00\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"data\",\r\n"
			+ "            \"supervisor\": \"data\",\r\n"
			+ "            \"batch\": \"data\",\r\n"
			+ "            \"date\": \"data\",\r\n"
			+ "            \"hour\": \"data\",\r\n"
			+ "            \"system\": \"data\",\r\n"
			+ "            \"user\": \"data\",\r\n"
			+ "            \"locationUser\": \"data\",\r\n"
			+ "            \"channelId\": \"data\",\r\n"
			+ "            \"instanceId\": \"data\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"cardNumber\": [\r\n"
			+ "                \"0005197120002018925\"\r\n"
			+ "            ],\r\n"
			+ "            \"accountNumber\": \"\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String CMC_REQUEST_CONCUENTAS_BAD = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"IVR\",\r\n"
			+ "        \"_serviceId\": \"InstallmentPurchases\",\r\n"
			+ "        \"_datetime\": \"2020-03-31T18:59:00\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"data\",\r\n"
			+ "            \"supervisor\": \"data\",\r\n"
			+ "            \"batch\": \"data\",\r\n"
			+ "            \"date\": \"data\",\r\n"
			+ "            \"hour\": \"data\",\r\n"
			+ "            \"system\": \"data\",\r\n"
			+ "            \"user\": \"data\",\r\n"
			+ "            \"locationUser\": \"data\",\r\n"
			+ "            \"channelId\": \"data\",\r\n"
			+ "            \"instanceId\": \"data\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"cardNumber\": [\r\n"
			+ "                \"9004073190324880502\"\r\n"
			+ "            ],\r\n"
			+ "            \"accountNumber\": \"\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String CMC_RESPONSE_CONCUENTAS = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Response\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"IVR\",\r\n"
			+ "        \"_serviceId\": \"InstallmentPurchases\",\r\n"
			+ "        \"_datetime\": \"2023-02-20T17:58:45\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"body\": [\r\n"
			+ "            {\r\n"
			+ "                \"logo\": \"103\",\r\n"
			+ "                \"logoDescription\": \"MASTERCARD BLACK\",\r\n"
			+ "                \"customerNumber\": \"0000000000003788388\",\r\n"
			+ "                \"accountNumber\": \"0005401030007604979\",\r\n"
			+ "                \"cardNumber\": \"0005197120002018925\",\r\n"
			+ "                \"cardHolder\": \"ISMAEL ANTONIO FRANCO MELENDEZ\",\r\n"
			+ "                \"productType\": \"TCA\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String CMC_REQUEST_SEMAFORO = "{\n"
			+ "    \"metadata\": {\n"
			+ "        \"_messageType\": \"Request\",\n"
			+ "        \"_messageId\": \"56c6eace-7c0c-4ae9-a68b-332fdf7145e1\",\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\n"
			+ "        \"_applicationId\": \"BTC\",\n"
			+ "        \"_serviceId\": \"OnlinePaymetBTC\",\n"
			+ "        \"_datetime\": \"2022-10-21T21:55:01\"\n"
			+ "    },\n"
			+ "    \"data\": {\n"
			+ "        \"body\": {\n"
			+ "            \"cardNumber\": \"0004215580003233354\", \n"
			+ "            \"action\": \"D\"\n"
			+ "        }\n"
			+ "    }\n"
			+ "}";
	
	public static final String CMC_REQUEST_MONPAGOS = "{\n"
			+ "    \"metadata\": {\n"
			+ "        \"_messageType\": \"Request\",\n"
			+ "        \"_messageId\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\n"
			+ "        \"_applicationId\": \"IVR\",\n"
			+ "        \"_serviceId\": \"onlinePayment\",\n"
			+ "        \"_datetime\": \"2021-10-06T11:00:00\"\n"
			+ "    },\n"
			+ "    \"data\": {\n"
			+ "        \"body\": {\n"
			+ "            \"requestType\":\"C\",\n"
			+ "            \"cardNumber\": \"0004406760054513008\",\n"
			+ "            \"maskedCardNumber\":\"\",\n"
			+ "            \"cardToken\":\"\"\n"
			+ "        }\n"
			+ "    }\n"
			+ "}";
	
	public static final String CMC_REQUEST_LISTADO = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_datetime\": \"2022-12-06T15:22:22\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_applicationId\": \"Loyalty\",\r\n"
			+ "        \"_serviceId\": \"loyaltyPointMaintenance\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_messageId\": \"3b60196b-cd6c-4c4e-ae83-e5fd9240cc90\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"cardNumber\": \"0005197120002018925\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String CMC_REQUEST_ONLINEDEBIT = "{\n"
			+ "    \"metadata\": {\n"
			+ "        \"_messageType\": \"Request\",\n"
			+ "        \"_messageId\": \"56c6eace-7c0c-4ae9-a68b-332fdf7145e1\",\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\n"
			+ "        \"_applicationId\": \"BTC\",\n"
			+ "        \"_serviceId\": \"OnlinePaymetBTC\",\n"
			+ "        \"_datetime\": \"2022-10-21T21:55:01\"\n"
			+ "    },\n"
			+ "    \"data\": {\n"
			+ "        \"body\": {\n"
			+ "            \"cardNumber\": \"0004215580003233354\", \n"
			+ "            \"action\": \"D\"\n"
			+ "        }\n"
			+ "    }\n"
			+ "}";
	
	public static final String CMC_RESPONSE_MONPAGOS = "{\r\n"
			+ "	    \"metadata\": {\r\n"
			+ "	        \"_messageType\": \"Response\",\r\n"
			+ "	        \"_messageId\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "	        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "	        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "	        \"_applicationId\": \"IVR\",\r\n"
			+ "	        \"_serviceId\": \"onlinePayment\",\r\n"
			+ "	        \"_datetime\": \"2023-03-06T20:56:18\"\r\n"
			+ "	    },\r\n"
			+ "	    \"data\": {\r\n"
			+ "	        \"body\": {\r\n"
			+ "	            \"totalBalance\": \"-1354.47\",\r\n"
			+ "	            \"delinquencyAmount\": \"0.00\",\r\n"
			+ "	            \"cardSequence\": \"1\",\r\n"
			+ "	            \"logo\": \"99\",\r\n"
			+ "	            \"customerNumber\": \"0000000000003788374\",\r\n"
			+ "	            \"cardExpirationDate\": \"1228\",\r\n"
			+ "	            \"coexFlag\": \"\",\r\n"
			+ "	            \"creditorName\": \"FRANCO/ISMAEL             \",\r\n"
			+ "	            \"planCash\": \"10001\",\r\n"
			+ "	            \"planRetail\": \"10002\",\r\n"
			+ "	            \"accountNumber\": \"0005400990005363863\"\r\n"
			+ "	        }\r\n"
			+ "	    }\r\n"
			+ "	}";
	
}
