package com.puntos.utils;

public class ConstantJsonIbs {
	
	public static final String IBS_REQUEST_CONSULTA = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"Loyalty\",\r\n"
			+ "        \"_serviceId\": \"pointsBalanceInquiry\",\r\n"
			+ "        \"_datetime\": \"2020-03-31T18:59:00\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"user\": \"user15\",\r\n"
			+ "            \"locationUser\": \"172.19.0.0\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"queryId\": \"0\",\r\n"
			+ "            \"inquiryType\": \"C\",\r\n"
			+ "            \"customerNumber\": [\"3516070\"],\r\n"
			+ "            \"accountNumber\": [],\r\n"
			+ "            \"cardNumber\": [],\r\n"
			+ "            \"pageNumber\": \"1\",\r\n"
			+ "            \"recordsPerPage\": \"1\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String IBS_RESPONSE_CONSULTA = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Response\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"Loyalty\",\r\n"
			+ "        \"_serviceId\": \"pointsBalanceInquiry\",\r\n"
			+ "        \"_datetime\": \"2023-02-20T17:17:33\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"queryId\": \"200223111729873\",\r\n"
			+ "            \"pageNumber\": \"1\",\r\n"
			+ "            \"recordsPerPage\": \"1\",\r\n"
			+ "            \"totalRecords\": \"4\",\r\n"
			+ "            \"totalPages\": \"4\",\r\n"
			+ "            \"customerPoints\": 108,\r\n"
			+ "            \"customerPointsExpiringNextPeriod\": 0,\r\n"
			+ "            \"customerCash\": 0.60,\r\n"
			+ "            \"responseCode\": \"000000\",\r\n"
			+ "            \"responseDescription\": \"Proceso finalizado normalmente\",\r\n"
			+ "            \"cardHolder\": \"\",\r\n"
			+ "            \"points\": [\r\n"
			+ "                {\r\n"
			+ "                    \"creditCardAccount\": \"0\",\r\n"
			+ "                    \"accountCash\": 0.00,\r\n"
			+ "                    \"accountPoints\": 0,\r\n"
			+ "                    \"accountBonus\": 48,\r\n"
			+ "                    \"accountTotalPoints\": 48,\r\n"
			+ "                    \"accountCashExpiringNextPeriod\": 0.00,\r\n"
			+ "                    \"accountPointsExpiringNextPeriod\": 0,\r\n"
			+ "                    \"accountBonusExpiringNextPeriod\": 0,\r\n"
			+ "                    \"accountType\": \"SAV\",\r\n"
			+ "                    \"cardNumber\": \"\",\r\n"
			+ "                    \"accountNumber\": \"003005976967\",\r\n"
			+ "                    \"customerNumber\": \"0000000000003516070\",\r\n"
			+ "                    \"customFillerInd1\": \"\",\r\n"
			+ "                    \"customFiller1\": \"\",\r\n"
			+ "                    \"customFillerInd2\": \"\",\r\n"
			+ "                    \"customFiller2\": \"\"\r\n"
			+ "                }\r\n"
			+ "            ]\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	
	public static final String IBS_REQUEST_MOVIMIENTO = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"d1c6d0b5-ad89-437b-b435-9913a260b965\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"OmnicanalPersonas\",\r\n"
			+ "        \"_serviceId\": \"inquiryMoveOfPoints\",\r\n"
			+ "        \"_datetime\": \"2022-01-31T21:51:33Z\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"user\": \"user15\",\r\n"
			+ "            \"locationUser\": \"172.19.0.0\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"accountNumber\": \"\",\r\n"
			+ "            \"cardNumber\": \"\",\r\n"
			+ "            \"megamileType\": \"\",\r\n"
			+ "            \"customerNumber\": \"10872\",\r\n"
			+ "            \"startDate\": \"20211117\",\r\n"
			+ "            \"finishDate\": \"20221117\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String IBS_RESPONSE_MOVIMIENTO =  "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Response\",\r\n"
			+ "        \"_messageId\": \"d1c6d0b5-ad89-437b-b435-9913a260b965\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"OmnicanalPersonas\",\r\n"
			+ "        \"_serviceId\": \"inquiryMoveOfPoints\",\r\n"
			+ "        \"_datetime\": \"2023-02-17T20:36:18\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": [\r\n"
			+ "            {\r\n"
			+ "                \"expirationDate\": \"0\",\r\n"
			+ "                \"transactionType\": \"0\",\r\n"
			+ "                \"transactionDescription\": \"\",\r\n"
			+ "                \"movementType\": \"\",\r\n"
			+ "                \"movementDescription\": \"\",\r\n"
			+ "                \"sign\": \"\",\r\n"
			+ "                \"movementPoints\": \"0\",\r\n"
			+ "                \"moventsDes\": \"\",\r\n"
			+ "                \"startPoints\": \"0\",\r\n"
			+ "                \"accountNumber\": \"\",\r\n"
			+ "                \"office\": \"\",\r\n"
			+ "                \"productType\": \"0\",\r\n"
			+ "                \"cardNumberT\": \"\",\r\n"
			+ "                \"creditCardAccount\": \"\",\r\n"
			+ "                \"customFillerInd1\": \"\",\r\n"
			+ "                \"customFiller1\": \"\",\r\n"
			+ "                \"customFillerInd2\": \"\",\r\n"
			+ "                \"customFiller2\": \"\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String IBS_ERROR_RESPONSE_WITHOUT_META =
			"{\r\n"
			+ "  \"metadata\": null,\r\n"
			+ "  \"errors\": [\r\n"
			+ "    {\r\n"
			+ "      \"code\": \"009041\",\r\n"
			+ "      \"title\": \"IBS\",\r\n"
			+ "      \"detail\": \"SOLICITUD RECHAZADA POR CTBL\"\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";

	public static final String JSON_ERROR =  
			"{\r\n"
			+ "  \"metadata\": {\r\n"
			+ "    \"_messageType\": \"Response\",\r\n"
			+ "    \"_messageId\": \"5e579759-e73a-4a36-9021-17084ca18ccc\",\r\n"
			+ "    \"_messageIdOrg\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "    \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "    \"_applicationId\": \"IVR\",\r\n"
			+ "    \"_serviceId\": \"movements\",\r\n"
			+ "    \"_datetime\": \"2022-10-25T20:48:30\"\r\n"
			+ "  },\r\n"
			+ "  \"errors\": [\r\n"
			+ "    {\r\n"
			+ "      \"code\": \"0039\",\r\n"
			+ "      \"title\": \"No hay datos para mostrar\",\r\n"
			+ "      \"detail\": \"No existen registros con la informacion proporcionada\"\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";

	public static final Object IBS_RESPONSE_CONSULTA_2 = "{\r\n"
			+ "   \"metadata\":{\r\n"
			+ "      \"_messageType\":\"Response\",\r\n"
			+ "      \"_datetime\":\"2023-07-11T08:41:48Z\"\r\n"
			+ "   },\r\n"
			+ "   \"data\":{\r\n"
			+ "      \"header\":{\r\n"
			+ "         \"date\":\"20230711\",\r\n"
			+ "         \"hour\":\"084148\"\r\n"
			+ "      },\r\n"
			+ "      \"body\":{\r\n"
			+ "         \"queryId\":\"110723084147716\",\r\n"
			+ "         \"pageNumber\":\"1\",\r\n"
			+ "         \"recordsPerPage\":\"20\",\r\n"
			+ "         \"totalRecords\":\"20\",\r\n"
			+ "         \"totalPages\":\"1\",\r\n"
			+ "         \"customerPoints\":\"2000000\",\r\n"
			+ "         \"customerPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "         \"customerCash\":\"20000.00\",\r\n"
			+ "         \"responseCode\":\"000000\",\r\n"
			+ "         \"responseDescription\":\"Proceso finalizado normalmente\",\r\n"
			+ "         \"cardHolder\":\"ANA JULIA RODRIGUEZ HERNANDEZ\",\r\n"
			+ "         \"points\":[\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010000656730\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010000826754\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010000845291\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010001003395\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010001043367\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010002353385\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010003838954\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010003951773\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010003959214\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010004244749\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010004516575\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010004633131\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010006649895\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010007162468\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010007544327\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010007644523\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400010009898713\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400020001233793\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5400990005363863\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            },\r\n"
			+ "            {\r\n"
			+ "               \"creditCardAccount\":\"5401060009673565\",\r\n"
			+ "               \"accountCash\":\"1000.00\",\r\n"
			+ "               \"accountPoints\":\"100000\",\r\n"
			+ "               \"accountBonus\":\"0\",\r\n"
			+ "               \"accountTotalPoints\":\"100000\",\r\n"
			+ "               \"accountCashExpiringNextPeriod\":\"0.00\",\r\n"
			+ "               \"accountPointsExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountBonusExpiringNextPeriod\":\"0\",\r\n"
			+ "               \"accountType\":\"TCR\",\r\n"
			+ "               \"cardNumber\":\"\",\r\n"
			+ "               \"accountNumber\":\"\",\r\n"
			+ "               \"customerNumber\":\"0000000000003788374\"\r\n"
			+ "            }\r\n"
			+ "         ]\r\n"
			+ "      }\r\n"
			+ "   }\r\n"
			+ "}";

}
