package com.puntos.utils;

public class ConstantJson {
	
	public static final String ORK_CONSULTA_REQUEST = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"Loyalty\",\r\n"
			+ "        \"_serviceId\": \"pointsBalanceInquiry\",\r\n"
			+ "        \"_datetime\": \"2020-03-31T18:59:00\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"user\": \"user15\",\r\n"
			+ "            \"locationUser\": \"172.19.0.0\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"queryId\": \"0\",\r\n"
			+ "            \"inquiryType\": \"C\",\r\n"
			+ "            \"customerNumber\": [\"3516070\"],\r\n"
			+ "            \"accountNumber\": [],\r\n"
			+ "            \"cardNumber\": [],\r\n"
			+ "            \"pageNumber\": \"1\",\r\n"
			+ "            \"recordsPerPage\": \"1\",\r\n"
			+ "            \"customFillerInd1\": \"\",\r\n"
			+ "            \"customFiller1\": \"\",\r\n"
			+ "            \"customFillerInd2\": \"\",\r\n"
			+ "            \"customFiller2\": \"\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_CONSULTA_REQUEST_BAD = "{\r\n"
			+ "	    \"metadata\": {\r\n"
			+ "	        \"_messageType\": \"Request\",\r\n"
			+ "	        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "	        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "	        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "	        \"_applicationId\": \"Loyalty\",\r\n"
			+ "	        \"_serviceId\": \"pointsBalanceInquiry\",\r\n"
			+ "	        \"_datetime\": \"2020-03-31T18:59:00\"\r\n"
			+ "	    },\r\n"
			+ "	    \"data\": {\r\n"
			+ "	        \"header\": {\r\n"
			+ "	            \"branch\": \"037\",\r\n"
			+ "	            \"supervisor\": \"0080\",\r\n"
			+ "	            \"batch\": \"0037\",\r\n"
			+ "	            \"date\": \"20211231\",\r\n"
			+ "	            \"hour\": \"142704\",\r\n"
			+ "	            \"system\": \"ALPHA10\",\r\n"
			+ "	            \"user\": \"user15\",\r\n"
			+ "	            \"locationUser\": \"172.19.0.0\",\r\n"
			+ "	            \"channelId\": \"000003711\",\r\n"
			+ "	            \"instanceId\": \"02\"\r\n"
			+ "	        },\r\n"
			+ "	        \"body\": {\r\n"
			+ "	            \"queryId\": \"0\",\r\n"
			+ "	            \"inquiryType\": \"C\",\r\n"
			+ "	            \"customerNumber\": [],\r\n"
			+ "	            \"accountNumber\": [],\r\n"
			+ "	            \"cardNumber\": [],\r\n"
			+ "	            \"pageNumber\": \"1\",\r\n"
			+ "	            \"recordsPerPage\": \"1\"\r\n"
			+ "	        }\r\n"
			+ "	    }\r\n"
			+ "	}";
	
	
	
	public static final String ORK_CONSULTA_RESPONSE = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Response\",\r\n"
			+ "        \"_messageId\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"Loyalty\",\r\n"
			+ "        \"_serviceId\": \"pointsBalanceInquiry\",\r\n"
			+ "        \"_datetime\": \"2023-02-20T17:17:33\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"queryId\": \"200223111729873\",\r\n"
			+ "            \"pageNumber\": \"1\",\r\n"
			+ "            \"recordsPerPage\": \"1\",\r\n"
			+ "            \"totalRecords\": \"4\",\r\n"
			+ "            \"totalPages\": \"4\",\r\n"
			+ "            \"customerPoints\": 108,\r\n"
			+ "            \"customerPointsExpiringNextPeriod\": 0,\r\n"
			+ "            \"customerCash\": 0.60,\r\n"
			+ "            \"responseCode\": \"000000\",\r\n"
			+ "            \"responseDescription\": \"Proceso finalizado normalmente\",\r\n"
			+ "            \"cardHolder\": \"\",\r\n"
			+ "            \"points\": [\r\n"
			+ "                {\r\n"
			+ "                    \"creditCardAccount\": \"0\",\r\n"
			+ "                    \"accountCash\": 0.00,\r\n"
			+ "                    \"accountPoints\": 0,\r\n"
			+ "                    \"accountBonus\": 48,\r\n"
			+ "                    \"accountTotalPoints\": 48,\r\n"
			+ "                    \"accountCashExpiringNextPeriod\": 0.00,\r\n"
			+ "                    \"accountPointsExpiringNextPeriod\": 0,\r\n"
			+ "                    \"accountBonusExpiringNextPeriod\": 0,\r\n"
			+ "                    \"accountType\": \"SAV\",\r\n"
			+ "                    \"cardNumber\": \"\",\r\n"
			+ "                    \"accountNumber\": \"003005976967\",\r\n"
			+ "                    \"customerNumber\": \"0000000000003516070\",\r\n"
			+ "                    \"customFillerInd1\": \"\",\r\n"
			+ "                    \"customFiller1\": \"\",\r\n"
			+ "                    \"customFillerInd2\": \"\",\r\n"
			+ "                    \"customFiller2\": \"\"\r\n"
			+ "                }\r\n"
			+ "            ]\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_MOVIMIENTO_REQUEST = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"d1c6d0b5-ad89-437b-b435-9913a260b965\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"OmnicanalPersonas\",\r\n"
			+ "        \"_serviceId\": \"inquiryMoveOfPoints\",\r\n"
			+ "        \"_datetime\": \"2022-01-31T21:51:33Z\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"user\": \"user15\",\r\n"
			+ "            \"locationUser\": \"172.19.0.0\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"accountNumber\": \"\",\r\n"
			+ "            \"cardNumber\": \"\",\r\n"
			+ "            \"megamileType\": \"\",\r\n"
			+ "            \"customerNumber\": \"10872\",\r\n"
			+ "            \"startDate\": \"20211117\",\r\n"
			+ "            \"finishDate\": \"20221117\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_MOVIMIENTO_REQUEST_BAD = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_messageId\": \"d1c6d0b5-ad89-437b-b435-9913a260b965\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"OmnicanalPersonas\",\r\n"
			+ "        \"_serviceId\": \"inquiryMoveOfPoints\",\r\n"
			+ "        \"_datetime\": \"2022-01-31T21:51:33Z\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"user\": \"user15\",\r\n"
			+ "            \"locationUser\": \"172.19.0.0\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"accountNumber\": \"\",\r\n"
			+ "            \"cardNumber\": \"\",\r\n"
			+ "            \"megamileType\": \"\",\r\n"
			+ "            \"customerNumber\": \"\",\r\n"
			+ "            \"startDate\": \"20211117\",\r\n"
			+ "            \"finishDate\": \"20221117\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_MOVIMIENTO_RESPONSE = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Response\",\r\n"
			+ "        \"_messageId\": \"d1c6d0b5-ad89-437b-b435-9913a260b965\",\r\n"
			+ "        \"_messageIdOrg\": \"e13a7e3e-7a59-40ea-b899-5a0f7f02cdcc\",\r\n"
			+ "        \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "        \"_applicationId\": \"OmnicanalPersonas\",\r\n"
			+ "        \"_serviceId\": \"inquiryMoveOfPoints\",\r\n"
			+ "        \"_datetime\": \"2023-02-21T22:32:30\"\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"batch\": \"0037\",\r\n"
			+ "            \"date\": \"20211231\",\r\n"
			+ "            \"hour\": \"142704\",\r\n"
			+ "            \"system\": \"ALPHA10\",\r\n"
			+ "            \"channelId\": \"000003711\",\r\n"
			+ "            \"instanceId\": \"02\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": [\r\n"
			+ "            {\r\n"
			+ "                \"expirationDate\": \"0\",\r\n"
			+ "                \"transactionType\": \"0\",\r\n"
			+ "                \"transactionDescription\": \"\",\r\n"
			+ "                \"movementType\": \"\",\r\n"
			+ "                \"movementDescription\": \"\",\r\n"
			+ "                \"sign\": \"\",\r\n"
			+ "                \"movementPoints\": \"0\",\r\n"
			+ "                \"moventsDes\": \"\",\r\n"
			+ "                \"startPoints\": \"0\",\r\n"
			+ "                \"accountNumber\": \"\",\r\n"
			+ "                \"office\": \"\",\r\n"
			+ "                \"productType\": \"0\",\r\n"
			+ "                \"cardNumberT\": \"\",\r\n"
			+ "                \"creditCardAccount\": \"\",\r\n"
			+ "                \"customFillerInd1\": \"\",\r\n"
			+ "                \"customFiller1\": \"\",\r\n"
			+ "                \"customFillerInd2\": \"\",\r\n"
			+ "                \"customFiller2\": \"\"\r\n"
			+ "            }\r\n"
			+ "        ]\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_REDENCION_REQUEST = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_datetime\": \"2022-11-23T17:30:00\",\r\n"
			+ "        \"_messageId\": 2231379,        \r\n"
			+ "        \"_serviceId\": \"pointsRedemption\",        \r\n"
			+ "        \"_messageIdOrg\": 2231379,\r\n"
			+ "        \"_applicationId\": \"EBP\",\r\n"
			+ "        \"_shortMessageId\": 2231379\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"user\": \"nmontes\",\r\n"
			+ "            \"date\": \"20221123\",\r\n"
			+ "            \"hour\": \"173000\",\r\n"
			+ "            \"batch\": \"3710\",\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"system\": \"EBP\",\r\n"
			+ "            \"channelId\": \"000003710\",\r\n"
			+ "            \"instanceId\": \"01\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"locationUser\": \"10.54.2.115\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"planCode\": \"00\",\r\n"
			+ "            \"lineCode\": \"29\",\r\n"
			+ "            \"itemCode\": \"0\",\r\n"
			+ "            \"groupCode\": \"0\",\r\n"
			+ "            \"providerCode\": \"0\",\r\n"
			+ "            \"numberOfItems\": \"01\",\r\n"
			+ "            \"beneficiaryName\": \"VILMA CAMPOS\",\r\n"
			+ "            \"lifemilesCustomerNumber\": \"\",\r\n"
			+ "            \"identificationDocumentNumber\": \"013141567\",\r\n"
			+ "            \"transactionCode\": \"2037\",\r\n"
			+ "            \"referenceNumber\": \"2022112311\",\r\n"
			+ "            \"customerNumber\": \"000010872\",\r\n"
			+ "            \"paymentInstrumentType\": \"TDC\",\r\n"
			+ "            \"operationType\": \"1\", \r\n"
			+ "            \"accountNumber\": \"\",\r\n"
			+ "            \"cardNumber\": \"0005197120004535041\",\r\n"
			+ "            \"transactionAmount\": \"10\",\r\n"
			+ "            \"merchantState\": \"SLV\",\r\n"
			+ "            \"merchantStore\": \"000003710\",\r\n"
			+ "            \"merchantName\": \"e-banca Personas\",\r\n"
			+ "            \"merchantCity\": \"San Salvador\",\r\n"
			+ "            \"customFiller2\": \"\",\r\n"
			+ "            \"customFiller1\": \"\",\r\n"
			+ "            \"customFillerInd1\": \"\",\r\n"
			+ "            \"customFillerInd2\": \"\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_REDENCION_REQUEST_BAD = "{\r\n"
			+ "    \"metadata\": {\r\n"
			+ "        \"_messageType\": \"Request\",\r\n"
			+ "        \"_datetime\": \"2022-11-23T17:30:00\",\r\n"
			+ "        \"_messageId\": 2231379,        \r\n"
			+ "        \"_serviceId\": \"pointsRedemption\",        \r\n"
			+ "        \"_messageIdOrg\": 2231379,\r\n"
			+ "        \"_applicationId\": \"EBP\",\r\n"
			+ "        \"_shortMessageId\": 2231379\r\n"
			+ "    },\r\n"
			+ "    \"data\": {\r\n"
			+ "        \"header\": {\r\n"
			+ "            \"user\": \"nmontes\",\r\n"
			+ "            \"date\": \"20221123\",\r\n"
			+ "            \"hour\": \"173000\",\r\n"
			+ "            \"batch\": \"3710\",\r\n"
			+ "            \"branch\": \"037\",\r\n"
			+ "            \"system\": \"EBP\",\r\n"
			+ "            \"channelId\": \"000003710\",\r\n"
			+ "            \"instanceId\": \"01\",\r\n"
			+ "            \"supervisor\": \"0080\",\r\n"
			+ "            \"locationUser\": \"10.54.2.115\"\r\n"
			+ "        },\r\n"
			+ "        \"body\": {\r\n"
			+ "            \"planCode\": \"00\",\r\n"
			+ "            \"lineCode\": \"29\",\r\n"
			+ "            \"itemCode\": \"0\",\r\n"
			+ "            \"groupCode\": \"0\",\r\n"
			+ "            \"providerCode\": \"0\",\r\n"
			+ "            \"numberOfItems\": \"01\",\r\n"
			+ "            \"beneficiaryName\": \"VILMA CAMPOS\",\r\n"
			+ "            \"lifemilesCustomerNumber\": \"\",\r\n"
			+ "            \"identificationDocumentNumber\": \"\",\r\n"
			+ "            \"transactionCode\": \"2037\",\r\n"
			+ "            \"referenceNumber\": \"2022112311\",\r\n"
			+ "            \"customerNumber\": \"000010872\",\r\n"
			+ "            \"paymentInstrumentType\": \"TDC\",\r\n"
			+ "            \"operationType\": \"1\", \r\n"
			+ "            \"accountNumber\": \"\",\r\n"
			+ "            \"cardNumber\": \"0005197120004535041\",\r\n"
			+ "            \"transactionAmount\": \"10\",\r\n"
			+ "            \"merchantState\": \"SLV\",\r\n"
			+ "            \"merchantStore\": \"000003710\",\r\n"
			+ "            \"merchantName\": \"e-banca Personas\",\r\n"
			+ "            \"merchantCity\": \"San Salvador\",\r\n"
			+ "            \"customFiller2\": \"\",\r\n"
			+ "            \"customFiller1\": \"\",\r\n"
			+ "            \"customFillerInd1\": \"\",\r\n"
			+ "            \"customFillerInd2\": \"\"\r\n"
			+ "        }\r\n"
			+ "    }\r\n"
			+ "}";
	
	public static final String ORK_REDENCION_RESPONSE = "";
	
	public static final String JSON_ERROR = 
			"{\r\n"
			+ "  \"metadata\": {\r\n"
			+ "    \"_messageType\": \"Response\",\r\n"
			+ "    \"_messageId\": \"5e579759-e73a-4a36-9021-17084ca18ccc\",\r\n"
			+ "    \"_messageIdOrg\": \"5a3b7c2e-2a85-23cf-el25-cf860954a92ef\",\r\n"
			+ "    \"_shortMessageId\": \"e13a7e3e-7a59-4\",\r\n"
			+ "    \"_applicationId\": \"IVR\",\r\n"
			+ "    \"_serviceId\": \"movements\",\r\n"
			+ "    \"_datetime\": \"2022-10-25T20:48:30\"\r\n"
			+ "  },\r\n"
			+ "  \"errors\": [\r\n"
			+ "    {\r\n"
			+ "      \"code\": \"0039\",\r\n"
			+ "      \"title\": \"No hay datos para mostrar\",\r\n"
			+ "      \"detail\": \"No existen registros con la informacion proporcionada\"\r\n"
			+ "    }\r\n"
			+ "  ]\r\n"
			+ "}";

}
